baseurl: 'https://tacgomes.com'
title: '#FIXME Blog'
metaDataFormat: yaml
DefaultContentLanguage: en
theme: beautifulhugo

pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsOptions: linenos=table

Permalinks:
  post: '/:year/:month/:day/:filename/'

Params:
  dateFormat: 'January 2, 2006'
  favicon: /blog/favicon.png
  comments: true
  rss: true
  staticman:
    api: https://staticman3.herokuapp.com/v3/entry/gitlab/tacgomes/blog/master/comments

Author:
  name: Tiago Gomes
  gitlab: tacgomes
  linkedin: tiagoacgomes

menu:
  main:
    - name: About
      url: page/about/
      weight: 3
